### ISSUE TITLE
如何指定音乐播放背景

### ISSUE THREAD

**Issue by judgelight** [Poppinrubo/HTML5VisualizationPlayer#1]
非常感谢提供了这个播放器，我感觉非常不错，并应用在了我的网站上 [https://luzhihua.com/audio](url)
不过我想改成让每一首音乐指定一副专门的图片，而不要随机图片，请教大神可以怎么改？
另外，如果可以的话，频谱改成圆形，加上发光效果，把歌曲信息放在中间的话效果就更好了。
参考[https://www.bilibili.com/video/av20272434](url)

**Comment by judgelight** [comment]
我加了一个传递参数来控制播放的音乐和图片，设置成打开页面随机播放歌曲。
并加入了倒影效果，和播放器面板自动隐藏，这样效果更好一些。
感谢大神提供的这个播放器，希望能继续改进，加入一点发光特效之类的。

**Comment by PoppinRubo** [comment]
play.config({
                autoPlay: false, //自动播放
                canvasId: "show", //canvas标签id
                button: { //设置生成的控制按钮,不设置button默认全部创建
                    prev: false, //上一首
                    play: true, //播放,暂停
                    next: true, //下一首
                    volume: true, //音量
                    progressControl: false, //是否开启进度控制
                },
                event: function (e) { //这是一个事件方法,点击控制按钮会传到此方法,点击想要扩展可以写在这个事件方法里
                    //参数:e.eventType 事件类型
                    //参数:e.describe 事件描述
                    if (e.eventType == "prev" || e.eventType == "next") {
                      //上一曲下一曲点击事件
                    }
                },
                playList: list
            });

**Comment by PoppinRubo** [comment]
可以在事件里面处理你的背景图 指定背景就行了

**Comment by PoppinRubo** [comment]
play.config({
                autoPlay: false, //自动播放
                canvasId: "show", //canvas标签id
                button: { //设置生成的控制按钮,不设置button默认全部创建
                    prev: false, //上一首
                    play: true, //播放,暂停
                    next: true, //下一首
                    volume: true, //音量
                    progressControl: false, //是否开启进度控制
                },
                event: function (e) { //这是一个事件方法,点击控制按钮会传到此方法,点击想要扩展可以写在这个事件方法里
                    //参数:e.eventType 事件类型
                    //参数:e.describe 事件描述
                    if (e.eventType == "prev" || e.eventType == "next") {
                      //上一曲  下一曲 事件
                        changBg();//改变背景图
                    }
                },
                playList: list
            });

**Comment by PoppinRubo** [comment]
bilibili 这个效果 有时间考虑弄一下

**Comment by judgelight** [comment]
bilibili视频中这个效果是用AE制作的，非常好看。js如果能做出来这种效果就好了
